#!/usr/bin/env bash
# This script creates a PID file, displays messages, and handles signals

terminate() {
    echo "I hate the kill command"
    cleanup
}

interrupt() {
    echo "Y U no love me?!"
}

quit() {
    echo "Y U no love me?!"
    cleanup
}

cleanup() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap terminate SIGTERM
trap interrupt SIGINT
trap quit SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
