#!/usr/bin/env bash
# Init script to manage the manage_my_process script

case "${1}" in
    start)
       ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        echo "manage_my_process stopped"
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
       ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
