#!/usr/bin/env bash
# Init script to manage the manage_my_process script

start() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process is already running."
    else
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f /var/run/my_process.pid ]; then
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
