#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"

for pid_dir in /proc/*/; do
    pid=$(basename "$pid_dir")
    
    if [[ $pid =~ ^[0-9]+$ ]]; then
        process_name=$(tr '\0' ' ' < "$pid_dir/cmdline" | grep -o 'bash')
        
        if [ -n "$process_name" ]; then
            echo "$pid bash"
        fi
    fi
done
