#!/usr/bin/env bash
# This script kills the process 7-highlander

pkill -f -SIGKILL 7-highlander
# if pkill -f -SIGKILL 7-highlander; then
#     echo "Killed"
# else
#     echo "Process not found"
# fi
