#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -rn
# awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -nr
