#!/usr/bin/env bash

hosts_file="/etc/hosts"
new_hosts_file="$HOME/hosts.new"

cp "$hosts_file" "$new_hosts_file"

sed -i 's/127.0.0.1/127.0.0.2/g' "$new_hosts_file"
echo "8.8.8.8 facebook.com" >> "$new_hosts_file"

cp -f "$new_hosts_file" "$hosts_file"
