#!/usr/bin/env bash

hosts_file="/etc/hosts"
new_hosts_file="$HOME/hosts.new"
ip_to_replace="127.0.0.1"
new_ip="127.0.0.2"

cp "$hosts_file" "$new_hosts_file"

sed "s/$ip_to_replace/$new_ip/g" "$new_hosts_file" > "$new_hosts_file.tmp" && mv "$new_hosts_file.tmp" "$new_hosts_file"

echo "8.8.8.8 facebook.com" >> "$new_hosts_file"

cp -f "$new_hosts_file" "$hosts_file"
